config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  root 'sessions#new'
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :content, presence: true, length: {maximum: 255}
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, :surname, length: {in: 1..20}
    validates :sexe, presence: true
    before_validation {name.upcase!}
    before_validation {surname.capitalize!}
    validates :email, presence: true, length: {maximum: 255}, uniqueness: true, 
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation {email.downcase!}
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    
    before_action :login_required

    private
    def login_required
        redirect_to new_session_path unless current_user
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :get_all_post, only: %i[ index create confirm ]

  def index
    @post = Post.new
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:info] = "Publication modifiée avec succès !!!"
      redirect_to user_path(current_user)
    else
      render "edit"
    end
  end

  def destroy
    @post.destroy
    flash[:danger] = "Publication supprimée !!!"
    redirect_to user_path(current_user.id)
  end

  def confirm
    @post = current_user.posts.build(post_params)
    render "posts/index" if @post.invalid?
  end

  def create
    @post = current_user.posts.build(post_params)
    if params[:back]
      render "index"
    else
      if @post.save
        redirect_to user_path(current_user.id)
        flash[:success] = "Publication enrégistrée !!!"
      else
        render :index
      end
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def get_all_post
    @posts = Post.all.order(created_at: :desc)
  end

  def post_params
    params.require(:post).permit(:image, :image_cache, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  def new
    redirect_to user_path(current_user) if current_user
  end

  def destroy
    session.delete(:user_id)
    flash[:danger] = "Déconnecté"
    redirect_to new_session_path
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Bienvenue sur votre profil de facebook clone"
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "Echec connexion. E-mail ou mot de passe incorrect"
      render "sessions/new"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :login_required, only: [:new, :create]

    def new
        @user = User.new
        redirect_to user_path(current_user) if current_user
    end

    def show
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to action: "show", id: @user.id
            flash[:success] = "Compte créé avec succès. Veuillez vous connecter"
        else
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:name, :surname, :sexe, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def choose_new_or_edit
        if action_name == 'index' || action_name == 'create'
          confirm_posts_path
        elsif action_name == 'edit'
          post_path
        end
    end

    def get_current_user_post
      @posts = Post.where(user_id: current_user.id).order(updated_at: :desc)
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        current_user.present?
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook Clone</title>
    <link rel="icon" type="images/png" href="/images/favicon-facebook.png"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/partials/_errors.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <p><%= notice %></p>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<footer class="bg-light text-center text-lg-start">
	  <div class="text-center p-3">
	    COPYRIGHT &COPY Août 2022, ALL RIGHTS RESERVED, Designed By Yakid
	  </div>
</footer>

app/views/partials/_form.html.erb
<%= form_with(model: @post, local: true, url: choose_new_or_edit) do |form| %>
    <% if @post.errors.any? %>
        <div class="alert alert-danger">
        <ul>
        <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
        </div>
    <% end %>
    <div class="form-group">
        <%= form.label :message%>
        <%= form.text_area :content, class: "form-control", rows: "3", placeholder: "Quoi de neuf ?" %>
    </div>
    <div class="form-group">
        <%= form.label :poster_une_image %>
        <%= form.file_field :image %>
        <%= form.hidden_field :image_cache %>
        <p class="help-block">choisir une image format png/jpg/jpeg</p>
    </div>
    <%= form.submit "Valider", class: "btn btn-primary" %>
<% end %>
<hr>

app/views/partials/_header-sign.html.erb
<nav class="navbar navbar-color">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="/posts/index">facebook</a>
	    </div>
		<% if logged_in?%>
		<ul class="nav navbar-nav">
			<li><a href="/posts/index"><i class="fas fa-home"></i> Accueil</a></li>
			<li><a href="/users/<%= current_user.id %>"><i class="fas fa-user"></i> Profil</a></li>
		</ul>
		<% end %>
	  	 <ul class="nav navbar-nav navbar-right">
		  <% if logged_in?%>
		  	<span class="badge"><%= current_user.name.first + current_user.surname.first %></span>
		  	<%= link_to "Déconnexion", session_path(current_user.id), method: :delete, class:"btn btn-danger navbar-btn btn-xs", data: { confirm: 'Au revoir et à la prochaine !!!' } %>
		  <% else %>
			  	<button onclick="location.href='/sessions/new';" class="btn btn-default navbar-btn">Connexion</button>
	      		<button onclick="location.href='/users/new';" class="btn btn-success navbar-btn">Inscription</button>
	      <% end %>
	    </ul>
	  </div>
</nav>

app/views/partials/_profil.html.erb
<div class="col-sm-3">
    <h2 class="text-center">MON PROFIL</h2>
    <div class="row text-center">
        <img class="rounded-circle" src="/images/user.png" alt="user" width="100%">
    </div>
    <div class="row line-2">
        <table class="table table-hover">
            <tr>
                <th>NOM</th>
                <td><%= current_user.name %></td>
            </tr>
            <tr>
                <th>PRENOM</th>
                <td><%= current_user.surname %></td>
            </tr>
            <tr>
                <th>SEXE</th>
                <td><%= current_user.sexe %></td>
            </tr>
            <tr>
                <th>EMAIL</th>
                <td><%= current_user.email %></td>
            </tr>
            <tr>
                <th>INSCRIT</th>
                <td>depuis le <%= current_user.created_at.to_s.to_time.strftime('%e-%m-%Y') %></td>
            </tr>
        </table>
        <div class="row text-center"><%= link_to "PUBLIER", posts_path, class: "btn btn-success" %></div>
    </div>

</div>

app/views/posts/confirm.html.erb
<div class="container">
    <div class="row" style="height: 50px"></div>
		<div class="row profile">
			<div class="col-sm-3">
				
			</div>
			<div class="col-sm-6">
				<h3 class="text-center">CONFIRMATION DE LA PUBLICATION</h3><hr>
                <%= form_with(model: @post, local: true) do |form| %>
                    <div class="form-group">
                      <label for="exampleInputEmail1">Message</label>
                      <p class="text-justify">
                          <%= @post.content %>
                      </p>
                      <%= form.hidden_field :content %>
                    </div>
                    <div class="form-group">
                      <label for="exampleInputFile">Photo à publier</label>
                      <div>
                        <%= image_tag @post.image.url, width: 200 if @post.image && @post.image.url %>
                      </div>
                      <%= form.hidden_field :image_cache %>
                    </div>
                    <%= form.submit "Valider", class: "btn btn-primary" %>
                    <%= form.submit "Retour", class: "btn btn-default", name: "back" %>
                <% end %>
                <p style="height: 130px"></p>
			</div>
		</div>
		<div class="row" style="height: 100px"></div>
</div>
<%= render "partials/footer" %>

app/views/posts/edit.html.erb
<%= render "partials/header-sign" %>

<div class="container">
    <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key} text-center") %>
    <% end %>
    <div class="row profile" style="">
        <%= render "partials/profil" %>
        <div class="col-sm-9 body-profile">
            <h3 class="text-center">MODIFIER LA PUBLICATION</h3><hr>
            <div class="row text">
                <div class="col-md-6 col-md-offset-3">
                    <%= render "partials/form" %>
                    <%= link_to "Annuler", user_path(current_user), class: "btn btn-default" %>
                </div>
            </div>
        </div>
        <div class="row" style="height: 15px"></div>
    </div>
    <div class="row" style="height: 65px"></div>
</div>
<%= render "partials/footer" %>

app/views/posts/index.html.erb
<%= render "partials/header-sign" %>

<div class="container">
		<div class="row profile">
			<div class="col-sm-3">
				<h2 class="text-center">PUBLIER</h2><hr>
                <%= render "partials/form" %>
			</div>
			<div class="col-sm-9 body-profile">
				<h3 class="text-center">
					LISTE DES PUBLICATIONS 
					<span class="label label-primary">
						<%= @posts.size %>
					</span>
				</h3>
				<hr>
                <div class="row">
					<% if @posts.size == 0 %>
					<div class="alert alert-info text-center">
						<p>Aucune publication trouvée...</p>
					</div>
					<% end %>
					<% @posts.each do |post| %>
					<div class="col-md-6">
						<div class="panel panel-primary" style="height: 300px; overflow: hidden">
							<div class="panel-heading">
                                <h3 class="panel-title"><%= post.user.name + ' ' + post.user.surname %></h3>
							    <h3 class="panel-title"><%= post.created_at.to_s.to_time.strftime('%e %B %Y à %k:%M') %></h3>
							</div>
							<div class="panel-body text-center">
                                <p class="text-justify">
									<%= post.content.capitalize %>
								</p>
								<%= image_tag post.image.url, height: 150, alt: "" if post.image && post.image.url %>
							</div>
						</div>
					</div>
					<% end %>
				</div>
			</div>
		</div>
		<div class="row" style="height: 65px"></div>
</div>

<%= render "partials/footer" %>

app/views/posts/show.html.erb
<%= render "partials/header-sign" %>

<div class="container">
    <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key} text-center") %>
    <% end %>
    <div class="row profile" style="">
        <%= render "partials/profil" %>
        <div class="col-sm-9 body-profile">
            <h3 class="text-center">DETAILS DE LA PUBLICATION</h3><hr>
            <div class="row text">
                <div class="col-md-12">
                    <div class="panel panel-primary" style="min-height:300px; overflow: auto">
                        <div class="panel-heading">
                            <h3 class="panel-title">Posté le : <%= @post.created_at.to_s.to_time.strftime('%e %B %Y à %k:%M') %></h3>
                            <h3 class="panel-title">Modifié le : <%= @post.updated_at.to_s.to_time.strftime('%e %B %Y à %k:%M') %></h3>
                            <div class="btn-group" role="group" aria-label="...">
                            <%= link_to 'Back', user_path(current_user), class: "btn btn-default btn-xs" %>
                            <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-info btn-xs" %>
                            </div>
                        </div>
                        <div class="panel-body text-center">
                            <p class="text-justify">
                                <%= @post.content.capitalize %>
                            </p>
                            <%= image_tag @post.image.url, height: 200, alt: "" if @post.image && @post.image.url %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="height: 15px"></div>
    </div>
    <div class="row" style="height: 65px"></div>
</div>
<%= render "partials/footer" %>

app/views/users/new.html.erb
<%= render "partials/header-sign" %>

	<div class="container">
		<div class="row">
			<div class="col-md-7 reseau">
				<img src="/images/reseau.png" alt="reseau" width="100%">
			</div>
			<div class="col-md-5">
				<h2>Inscription</h2>
				<p>C'est gratuit (et ça le restera toujours)</p>
				<%= render "partials/errors"%>
				<%= form_with(model: @user, local: true, class: "form-horizontal") do |form| %>
				<div class="form-group">
			      <div class="col-xs-6">
			        <%= form.text_field :surname, class: "form-control", placeholder: "Prénom"%>
			      </div>
			      <div class="col-xs-6">
			        <%= form.text_field :name, class: "form-control", placeholder: "Nom de famille"%>
			      </div>
			    </div>
			    <div class="form-group">
			      <div class="col-sm-12">
			        <%= form.email_field :email, class: "form-control", placeholder: "Adresse email"%>
			      </div>
			    </div>
			    <div class="form-group">
			      <div class="col-sm-12">          
			        <%= form.password_field :password, class: "form-control", placeholder: "Nouveau mot de passe"%>
			      </div>
			    </div>
			    <div class="form-group">
			      <div class="col-sm-12">          
			        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirmer mot de passe"%>
			      </div>
			    </div>
			    <div class="form-group">        
			      <div class="col-sm-12">
			        <div class="checkbox">
				        <label class="radio-inline">
                
                  <%= form.radio_button :sexe, "Homme" %> Homme
						    </label>
                <label class="radio-inline">
                  <%= form.radio_button :sexe, "Femme" %> Femme
						    </label>
			        </div>
			      </div>
			    </div>
			    <p>
			    	En appuyant sur S’inscrire, vous acceptez nos <a href="#">Conditions générales</a>, notre <a href="#">Politique d’utilisation des données</a> et notre <a href="#">Politique d’utilisation des cookies</a>. Vous recevrez peut-être des notifications par texto de notre part et vous pouvez à tout moment vous désabonner.
			    </p>
			    <div class="form-group">        
			      <div class="col-sm-10">
			        <button type="submit" class="btn btn-success btn-lg">Inscription</button>
			      </div>
			    </div>
			  <% end %>
			</div>
			<div class="row" style="height: 0"></div>
		</div>
		<div class="row" style="height: 50px"></div>
	</div>

	<%= render "partials/footer" %>

app/views/users/show.html.erb
<%= render "partials/header-sign" %>

<div class="container">
        <% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key} text-center") %>
		<% end %>
		<div class="row profile">
			<%= render "partials/profil" %>
			<div class="col-sm-9 body-profile">
				<h3 class="text-center">
					MES PUBLICATIONS 
					<span class="label label-primary">
						<%= get_current_user_post.size %>
					</span>
				</h3>
				<hr>
                <div class="row">
					<% if get_current_user_post.size == 0 %>
					<div class="alert alert-info text-center">
						<p>Aucune publication trouvée...</p>
					</div>
					<% end %>
					<% get_current_user_post.each do |post| %>
                    <div class="col-md-6">
						<div class="panel panel-primary" style="height: 250px; overflow: hidden">
							<div class="panel-heading">
							  <h3 class="panel-title"><%= post.created_at.to_s.to_time.strftime('%e %B %Y à %k:%M') %></h3>
							  <div class="btn-group" role="group" aria-label="...">
								<%= link_to 'Show', post, class: "btn btn-default btn-xs" %>
								<%= link_to 'Edit', edit_post_path(post), class: "btn btn-info btn-xs" %>
								<%= link_to 'Delete', post, method: :delete, class: "btn btn-danger btn-xs", data: { confirm: 'Vous êtes sûr de vouloir supprimer cette publication ?' } %>
							  </div>
							</div>
							<div class="panel-body text-center">
								<%= image_tag post.image.url, height: 150, alt: "" if post.image && post.image.url %>
								<p class="text-justify">
									<%= post.content.split(' ').first.capitalize if post.content && post.content.split(' ').first%> ... <em>(voir la suite)</em>
								</p>
							</div>
						</div>
					</div>
                    <% end %>
				</div>
			</div>
		</div>
		<div class="row" style="height: 65px"></div>
	</div>
	<%= render "partials/footer" %>